### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by juanse417** [4ARMED/csp-generator#1]
Hello,

I've followed the steps detailed on the Readme. But I can't seem to make it work

I my docker up and running

`CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                      NAMES
dd67da0eec10        4armed/nginx         "nginx"                  45 seconds ago      Up 43 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   csp-generator_frontend_1
a64acdd2008a        4armed/csp-backend   "bundle exec foreman…"   3 hours ago         Up 44 seconds       4567/tcp                                   csp-generator_sinatra_1
a9fc707b75ae        4armed/mongo         "/entrypoint.sh /run…"   3 hours ago         Up 45 seconds       27017/tcp                                  csp-generator_mongo_1`

But if I go to localhost:4567 I just get Error.
And when I visit localhost:80 I get a <h1>Not Found</h1>

with my docker-compse loggin as below:

`mongo_1     | 2018-11-08T17:10:33.021+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
mongo_1     | 2018-11-08T17:10:33.033+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo_1     | 2018-11-08T17:10:33.033+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
mongo_1     | 2018-11-08T17:10:33.033+0000 I STORAGE  [initandlisten] 
mongo_1     | 2018-11-08T17:10:33.033+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1     | 2018-11-08T17:10:33.034+0000 I STORAGE  [initandlisten] See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1     | 2018-11-08T17:10:33.035+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1461M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
mongo_1     | 2018-11-08T17:10:33.358+0000 I CONTROL  [initandlisten] 
mongo_1     | 2018-11-08T17:10:33.358+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1     | 2018-11-08T17:10:33.358+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1     | 2018-11-08T17:10:33.358+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
mongo_1     | 2018-11-08T17:10:33.358+0000 I CONTROL  [initandlisten] 
mongo_1     | 2018-11-08T17:10:33.371+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1     | 2018-11-08T17:10:33.371+0000 I NETWORK  [thread1] waiting for connections on port 27017
mongo_1     | 2018-11-08T17:10:34.061+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK
mongo_1     | mongod
sinatra_1   | 17:14:33 web.1  | 172.17.0.1 - - [08/Nov/2018:17:14:33 +0000] "GET / HTTP/1.0" 404 18 0.0055
`

What I'm missing? 

I'm new at using docker 

Thanks!

**Comment by marcwickenden** [comment]
There isn't a page at / so that might be why you get an error. Try going to http://localhost/csptest.html.

**Comment by juanse417** [comment]
Now I feel dumb 😅
I can see chuck Norris. 

Now I'm just getting in the developer console:

`POST http://localhost/report 504 (Gateway Time-out)`

And my docker-compose:
`mongo_1     | mongod
sinatra_1   | 17:41:53 web.1  | 172.17.0.1 - - [08/Nov/2018:17:41:53 +0000] "GET /csptest.html HTTP/1.0" 304 - 0.0087
sinatra_1   | 17:41:54 web.1  | 172.17.0.1 - - [08/Nov/2018:17:41:54 +0000] "GET /favicon.ico HTTP/1.0" 200 - 0.0008
sinatra_1   | 17:41:59 web.1  | 172.17.0.1 - - [08/Nov/2018:17:41:59 +0000] "GET /csptest.html HTTP/1.0" 304 - 0.0024
sinatra_1   | 17:42:19 web.1  | 2018-11-08 17:42:19 - Mongo::Error::NoServerAvailable - No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47056267710680 tag_sets=[] max_staleness=nil> using server_selection_timeout=10 and local_threshold=0.015:
`

Thanks

**Comment by marcwickenden** [comment]
That looks like more of an issue. The Mongo server has gone away. The Sinatra app will die when that happens and that's why you'll get a 504. Can you provide the output of `docker-compose ps` and maybe `docker-compose logs`?

**Comment by juanse417** [comment]
docker-compose ps:

```
csp-generator_frontend_1   nginx                            Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
csp-generator_mongo_1      /entrypoint.sh /run.sh           Up      27017/tcp                               
csp-generator_sinatra_1    bundle exec foreman start  ...   Up      4567/tcp
```

docker-compose logs:

```
Attaching to csp-generator_mongo_1, csp-generator_sinatra_1, csp-generator_frontend_1
mongo_1     | => Starting mongod
mongo_1     | => sleeping to let mongod start
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten] MongoDB starting : pid=8 port=27017 dbpath=/data/db 64-bit host=e5369921dae6
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten] db version v3.4.0
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten] git version: f4240c60f005be757399042dc12f6addbc3170c1
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten] modules: none
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten] build environment:
sinatra_1   | 17:41:12 web.1  | started with pid 7
mongo_1     | 2018-11-08T17:41:10.788+0000 I CONTROL  [initandlisten]     distmod: debian81
mongo_1     | 2018-11-08T17:41:10.789+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1     | 2018-11-08T17:41:10.789+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1     | 2018-11-08T17:41:10.789+0000 I CONTROL  [initandlisten] options: {}
mongo_1     | 2018-11-08T17:41:10.794+0000 I STORAGE  [initandlisten] 
mongo_1     | 2018-11-08T17:41:10.794+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1     | 2018-11-08T17:41:10.794+0000 I STORAGE  [initandlisten] See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1     | 2018-11-08T17:41:10.794+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1461M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
mongo_1     | 2018-11-08T17:41:10.884+0000 I CONTROL  [initandlisten] 
mongo_1     | 2018-11-08T17:41:10.884+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1     | 2018-11-08T17:41:10.884+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1     | 2018-11-08T17:41:10.884+0000 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
mongo_1     | 2018-11-08T17:41:10.884+0000 I CONTROL  [initandlisten] 
mongo_1     | 2018-11-08T17:41:10.901+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1     | 2018-11-08T17:41:10.918+0000 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
mongo_1     | 2018-11-08T17:41:10.918+0000 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1     | 2018-11-08T17:41:10.921+0000 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
mongo_1     | 2018-11-08T17:41:10.925+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
mongo_1     | 2018-11-08T17:41:10.926+0000 I NETWORK  [thread1] waiting for connections on port 27017
mongo_1     | => Executing startup script with /data/scripts/initCSP.js
mongo_1     | MongoDB shell version v3.4.0
mongo_1     | connecting to: mongodb://127.0.0.1:27017
mongo_1     | 2018-11-08T17:41:16.016+0000 I NETWORK  [thread1] connection accepted from 127.0.0.1:58118 #1 (1 connection now open)
mongo_1     | 2018-11-08T17:41:16.024+0000 I NETWORK  [conn1] received client metadata from 127.0.0.1:58118 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.0" }, os: { type: "Linux", name: "PRETTY_NAME="Debian GNU/Linux 8 (jessie)"", architecture: "x86_64", version: "Kernel 4.9.93-linuxkit-aufs" } }
mongo_1     | MongoDB server version: 3.4.0
mongo_1     | switched to db csp
mongo_1     | WriteResult({ "nRemoved" : 0 })
mongo_1     | 2018-11-08T17:41:16.074+0000 I INDEX    [conn1] build index on: csp.csp properties: { v: 2, unique: true, key: { csp-report.document-uri: 1.0, csp-report.blocked-uri: 1.0 }, name: "csp-report.document-uri_1_csp-report.blocked-uri_1", ns: "csp.csp" }
mongo_1     | 2018-11-08T17:41:16.074+0000 I INDEX    [conn1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
mongo_1     | 2018-11-08T17:41:16.076+0000 I INDEX    [conn1] build index done.  scanned 0 total records. 0 secs
mongo_1     | {
mongo_1     | 	"createdCollectionAutomatically" : true,
mongo_1     | 	"numIndexesBefore" : 1,
mongo_1     | 	"numIndexesAfter" : 2,
mongo_1     | 	"ok" : 1
mongo_1     | }
mongo_1     | bye
mongo_1     | 2018-11-08T17:41:16.096+0000 I -        [conn1] end connection 127.0.0.1:58118 (1 connection now open)
mongo_1     | mongod
sinatra_1   | 17:41:53 web.1  | 172.17.0.1 - - [08/Nov/2018:17:41:53 +0000] "GET /csptest.html HTTP/1.0" 304 - 0.0087
sinatra_1   | 17:41:54 web.1  | 172.17.0.1 - - [08/Nov/2018:17:41:54 +0000] "GET /favicon.ico HTTP/1.0" 200 - 0.0008
sinatra_1   | 17:41:59 web.1  | 172.17.0.1 - - [08/Nov/2018:17:41:59 +0000] "GET /csptest.html HTTP/1.0" 304 - 0.0024
sinatra_1   | 17:42:19 web.1  | 2018-11-08 17:42:19 - Mongo::Error::NoServerAvailable - No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47056267710680 tag_sets=[] max_staleness=nil> using server_selection_timeout=10 and local_threshold=0.015:
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/server_selector/selectable.rb:110:in `select_server'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/cluster.rb:256:in `next_primary'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/retryable.rb:150:in `legacy_write_with_retry'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/retryable.rb:103:in `write_with_retry'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/collection.rb:422:in `block in insert_one'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/cluster.rb:517:in `with_session'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/client.rb:449:in `with_session'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/mongo-2.5.3/lib/mongo/collection.rb:421:in `insert_one'
sinatra_1   | 17:42:19 web.1  | 	/app/app.rb:110:in `block in <top (required)>'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:231:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:224:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/handler/thin.rb:22:in `run'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:297:in `start'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/server.rb:148:in `start'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/bin/rackup:4:in `<top (required)>'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/bin/rackup:23:in `load'
sinatra_1   | 17:42:19 web.1  | 	/app/vendor/bundle/ruby/2.4.0/bin/rackup:23:in `<top (required)>'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `load'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:28:in `run'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli.rb:424:in `exec'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli.rb:27:in `dispatch'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/cli.rb:18:in `start'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/exe/bundle:30:in `block in <top (required)>'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.5/exe/bundle:22:in `<top (required)>'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/bundle/bin/bundle:23:in `load'
sinatra_1   | 17:42:19 web.1  | 	/usr/local/bundle/bin/bundle:23:in `<main>'
sinatra_1   | 17:42:19 web.1  | 172.17.0.1 - - [08/Nov/2018:17:42:19 +0000] "POST /report HTTP/1.0" 500 30 20.0218
sinatra_1   | 17:42:40 web.1  | 2018-11-08 17:42:40 - Mongo::Error::NoServerAvailable - No server is available matching preference: #<Mongo::ServerSelector::Primary:0x47056267710680 tag_sets=[] max_staleness=nil> using server_selection_timeout=10 and local_threshold=0.015:
```

**Comment by marcwickenden** [comment]
Ok, looks like it's an environment variable name mismatch between the csp-backend container and the values specified in docker-compose.yml. That should be a simple fix. Hold on.
